CREATE TABLE IF NOT EXISTS APPENDICES
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_appendices_number INTEGER                                 NOT NULL,
    appendices_name              VARCHAR                                 NOT NULL,
    CONSTRAINT pk_appendices PRIMARY KEY (id),
    CONSTRAINT UQ_APPENDICES UNIQUE (appendices_name)
);

CREATE TABLE IF NOT EXISTS PAGE_TITLES
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    documentType            VARCHAR                                 NOT NULL,
    organization_id         BIGINT,
    organization_full_name  BOOLEAN,
    organization_license    BOOLEAN,
    requisites_organization BOOLEAN,
    branch_id               BIGINT,
    branch_full_name        BOOLEAN,
    branch_requisites       BOOLEAN,
    license_branch          BOOLEAN,
    department_id           BIGINT,
    department_full_name    BOOLEAN,
    department_requisites   BOOLEAN,
    department_license      BOOLEAN,
    CONSTRAINT pk_pageTitle PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS COLUMNS_HEADERS
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_cell_number INTEGER                                 NOT NULL,
    cell_name              VARCHAR                                 NOT NULL,
    CONSTRAINT pk_columnHeader PRIMARY KEY (id),
    CONSTRAINT UQ_COLUMNS_HEADERS UNIQUE (sequential_cell_number, cell_name)
);

CREATE TABLE IF NOT EXISTS TABLE_HEADER_TEMPLATES
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_data_type         VARCHAR                                 NOT NULL,
    sequential_table_number INTEGER                                 NOT NULL,
    table_name              VARCHAR                                 NOT NULL,
    CONSTRAINT pk_tableHeaderTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_TABLE_HEADER_TEMPLATES UNIQUE (table_data_type, sequential_table_number, table_name)
);

CREATE TABLE IF NOT EXISTS TABLE_HEADER_TEMPLATES_COLUMNS_HEADERS
(
    table_header_template_id BIGINT,
    columns_header_id        BIGINT,
    CONSTRAINT pk_table_header_templates_of_columns_headers PRIMARY KEY (table_header_template_id, columns_header_id)
);

CREATE TABLE IF NOT EXISTS CONCLUSIONS_TEMPLATES
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    approaching_defect VARCHAR,
    equal_defect       VARCHAR,
    is_defect          VARCHAR,
    is_not_defect      VARCHAR,
    no_norm_defect     VARCHAR,
    CONSTRAINT pk_conclusionTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS RECOMMENDATIONS
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    objectType_id       BIGINT                                  NOT NULL,
    recommendation_text VARCHAR                                 NOT NULL,
    CONSTRAINT pk_recommendation PRIMARY KEY (id),
    CONSTRAINT UQ_RECOMMENDATIONS UNIQUE (objectType_id, recommendation_text)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_TEMPLATES
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_type_subsection         VARCHAR                                 NOT NULL,
    sequential_subsection_number INTEGER                                 NOT NULL,
    subsection_name              VARCHAR                                 NOT NULL,
    subsection_text              VARCHAR,
    conclusions_template_id      BIGINT,
    CONSTRAINT pk_subsectionTemplate PRIMARY KEY (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_CONCLUSION_TEMPLATES FOREIGN KEY (conclusions_template_id)
        REFERENCES conclusions_templates (id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_TEMPLATES_RECOMMENDATIONS
(
    subsection_template_id BIGINT,
    recommendation_id      BIGINT,
    CONSTRAINT pk_subsection_templates_of_recommendations PRIMARY KEY (subsection_template_id, recommendation_id)
);

CREATE TABLE IF NOT EXISTS REPORTS_TEMPLATES
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    page_title_id  BIGINT                                  NOT NULL,
    document_name  VARCHAR                                 NOT NULL,
    document_title VARCHAR                                 NOT NULL,
    CONSTRAINT pk_reportTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS REPORTS_TEMPLATES_SUBSECTION_TEMPLATES
(
    reports_template_id    BIGINT,
    subsection_template_id BIGINT,
    CONSTRAINT pk_reports_templates_table_of_subsection_templates
        PRIMARY KEY (reports_template_id, subsection_template_id)
);

CREATE TABLE IF NOT EXISTS REPORTS_TEMPLATES_SUBSECTION_TEMPLATES
(
    reports_template_id    BIGINT,
    appendices_id BIGINT,
    CONSTRAINT pk_reports_templates_table_of_appendices
        PRIMARY KEY (reports_template_id, appendices_id)
);
