CREATE TABLE IF NOT EXISTS APPENDICES_TEMPLATES
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_appendices_number INTEGER                                 NOT NULL,
    appendices_name              VARCHAR                                 NOT NULL,
    CONSTRAINT pk_appendices PRIMARY KEY (id),
    CONSTRAINT UQ_APPENDICES_TEMPLATES UNIQUE (appendices_name)
);

CREATE TABLE IF NOT EXISTS PAGE_TITLE_TEMPLATES
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization            VARCHAR,
    organization_license    VARCHAR,
    requisites_organization VARCHAR,
    branch                  VARCHAR,
    branch_requisites       VARCHAR,
    license_branch          VARCHAR,
    department              VARCHAR,
    department_requisites   VARCHAR,
    department_license      VARCHAR,
    document_name           VARCHAR,
    document_title          VARCHAR,
    CONSTRAINT pk_pageTitleTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS COLUMNS_HEADERS_TEMPLATES
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_cell_number INTEGER                                 NOT NULL,
    cell_name              VARCHAR                                 NOT NULL,
    CONSTRAINT pk_columnHeader PRIMARY KEY (id),
    CONSTRAINT UQ_COLUMNS_HEADERS_TEMPLATES UNIQUE (sequential_cell_number, cell_name)
);

CREATE TABLE IF NOT EXISTS TABLE_TEMPLATES
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_data_type         VARCHAR                                 NOT NULL,
    sequential_table_number INTEGER                                 NOT NULL,
    table_name              VARCHAR                                 NOT NULL,
    CONSTRAINT pk_tableTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_TABLE_TEMPLATES UNIQUE (table_data_type, sequential_table_number, table_name)
);

CREATE TABLE IF NOT EXISTS TABLE_TEMPLATES_COLUMNS_HEADERS_TEMPLATES
(
    table_template_id BIGINT,
    columns_header_id BIGINT,
    CONSTRAINT pk_table_templates_of_columns_headers_template PRIMARY KEY (table_template_id, columns_header_id)
);

CREATE TABLE IF NOT EXISTS CONCLUSIONS_TEMPLATES
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    approaching_defect VARCHAR,
    equal_defect       VARCHAR,
    is_defect          VARCHAR,
    is_not_defect      VARCHAR,
    no_norm_defect     VARCHAR,
    CONSTRAINT pk_conclusionTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS RECOMMENDATIONS_TEMPLATES
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    objectType_id       BIGINT                                  NOT NULL,
    recommendation_text VARCHAR                                 NOT NULL,
    CONSTRAINT pk_recommendationTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_RECOMMENDATIONS_TEMPLATES UNIQUE (objectType_id, recommendation_text)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_TEMPLATES
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subsection_data_type         VARCHAR                                 NOT NULL,
    sequential_subsection_number INTEGER                                 NOT NULL,
    subsection_name              VARCHAR                                 NOT NULL,
    subsection_text              VARCHAR,
    conclusions_template_id      BIGINT,
    subsection_number            BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_subsectionTemplate PRIMARY KEY (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_CONCLUSION_TEMPLATES FOREIGN KEY (conclusions_template_id)
        REFERENCES conclusions_templates (id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_TEMPLATES_RECOMMENDATIONS
(
    subsection_template_id BIGINT,
    recommendation_id      BIGINT,
    CONSTRAINT pk_subsection_templates_of_recommendations PRIMARY KEY (subsection_template_id, recommendation_id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_TEMPLATES
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    objects_type_id            BIGINT                                  NOT NULL,
    reporting_document_id      BIGINT                                  NOT NULL,
    page_header_id             BIGINT                                  NOT NULL,
    sequential_protocol_number INTEGER                                 NOT NULL,
    protocol_name              VARCHAR                                 NOT NULL,
    protocol_title             VARCHAR                                 NOT NULL,
    conclusions_template_id    BIGINT,
    CONSTRAINT pk_protocolTemplate PRIMARY KEY (id),
    CONSTRAINT FK_PROTOCOL_TEMPLATES_ON_CONCLUSIONS_TEMPLATES
        FOREIGN KEY (conclusions_template_id)
            REFERENCES conclusions_templates (id),
    CONSTRAINT FK_PROTOCOL_TEMPLATES_ON_PAGE_TITLES_TEMPLATES FOREIGN KEY (page_header_id) REFERENCES page_title_templates (id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_TEMPLATES_SUBSECTION_TEMPLATES
(
    protocol_template_id    BIGINT,
    subsections_template_id BIGINT,
    CONSTRAINT pk_protocol_templates_of_subsections_templates PRIMARY KEY (protocol_template_id, subsections_template_id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_TEMPLATES_TABLE_TEMPLATES
(
    protocol_template_id BIGINT,
    table_template_id    BIGINT,
    CONSTRAINT pk_protocol_templates_of_table_header_templates
        PRIMARY KEY (protocol_template_id, table_template_id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_TEMPLATES_APPENDICES
(
    protocol_template_id BIGINT,
    appendices_id        BIGINT,
    CONSTRAINT pk_protocol_templates_of_appendices PRIMARY KEY (protocol_template_id, appendices_id)
);

CREATE TABLE IF NOT EXISTS SECTION_TEMPLATES
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_section_number INTEGER                                 NOT NULL,
    section_name              VARCHAR                                 NOT NULL,
    CONSTRAINT pk_sectionTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS SECTION_TEMPLATES_SUBSECTION_TEMPLATES
(
    section_template_id     BIGINT,
    subsections_template_id BIGINT,
    CONSTRAINT pk_sections_templates_of_subsections_templates PRIMARY KEY (section_template_id, subsections_template_id)
);

CREATE TABLE IF NOT EXISTS SECTION_TEMPLATES_REPORT_PROTOCOL_TEMPLATES
(
    section_template_id         BIGINT,
    report_protocol_template_id BIGINT,
    CONSTRAINT pk_section_templates_of_report_protocol_templates
        PRIMARY KEY (section_template_id, report_protocol_template_id)
);

CREATE TABLE IF NOT EXISTS SECTION_TEMPLATES_RECOMMENDATIONS
(
    section_template_id BIGINT,
    recommendation_id   BIGINT,
    CONSTRAINT pk_section_templates_of_recommendations PRIMARY KEY (section_template_id, recommendation_id)
);

CREATE TABLE IF NOT EXISTS SECTION_TEMPLATES_APPENDICES
(
    section_template_id BIGINT,
    appendices_id       BIGINT,
    CONSTRAINT pk_section_templates_of_appendices PRIMARY KEY (section_template_id, appendices_id)
);

CREATE TABLE IF NOT EXISTS REPORT_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    objects_type_id       BIGINT                                  NOT NULL,
    reporting_document_id BIGINT                                  NOT NULL,
    title_page_header_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_reportTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_REPORT_TEMPLATES UNIQUE (objects_type_id, reporting_document_id),
    CONSTRAINT FK_PROTOCOL_TEMPLATES_ON_PAGE_TITLES_TEMPLATES FOREIGN KEY (title_page_header_id) REFERENCES page_title_templates (id)
);

CREATE TABLE IF NOT EXISTS REPORT_TEMPLATES_SECTION_TEMPLATES
(
    report_template_id  BIGINT,
    section_template_id BIGINT,
    CONSTRAINT pk_report_templates_of_sections_templates PRIMARY KEY (report_template_id, section_template_id)
);