package ru.nabokovsg.temlservice.enums;

public enum TableDataType {

    VISUAL_MEASURING_CONTROL,
    ULTRASONIC_MEASURING_CONTROL,
    ULTRASONIC_CONTROL,
    HARDNESS_MEASURING,
    REFERENCE_POINT_MEASURING,
    CONTROL_POINT_MEASURING,
    REPAIRS_DATA,
    SURVEYS_DATA
}