package ru.nabokovsg.temlservice.models;

public enum ColumnDataType {

    SEQUENCE_NUMBER,
    ELEMENT,
    SUB_ELEMENT,
    DEFECT,
    REPAIR,
    REFERENCE_POINT_NUMBER,
    REFERENCE_POINT_MEASURING,
    DEVIATION_YEAR,
    DEVIATION,
    PRECIPITATION,
    CONTROL_POINT_NUMBER,
    CONTROL_POINT_MEASURING,
    ADJACENT_CONTROL_POINTS,
    DIAMETRIC_CONTROL_POINT
}